/**
 * @description Constants for DOM module
 */
public class DOM_Config {
    public static final String SPAM_EXTENSION_STATUS          = 'SPAM';
    public static final String LANG_EXTENSION_STATUS          = 'LANG';
    public static final String DRV_EXTENSION_STATUS           = 'DRV';
    public static final String ENT_EXTENSION_STATUS           = 'ENT';

    public static final String LAUNCH_RESULT_EXTENSION_STATUS = 'LANG';
}
